# Generated by Django 2.1.4 on 2019-01-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20190103_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
