# Generated by Django 2.1.4 on 2019-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20190114_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='actualizado',
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo',
            field=models.TextField(blank=True),
        ),
    ]
