# Generated by Django 2.1.4 on 2019-07-21 21:31

from django.db import migrations, models
import django.db.models.deletion
import paciente.models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20190429_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivopdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to=paciente.models.Archivopdf._generar_ruta_imagen)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
