# Generated by Django 2.1.4 on 2019-07-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_archivopdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivopdf',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivopdf',
            name='fecha_documento',
            field=models.DateField(auto_now=True),
        ),
    ]
