# Generated by Django 2.1.4 on 2019-07-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20190721_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivopdf',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
