# Generated by Django 2.1.4 on 2019-07-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_paciente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
