# Generated by Django 2.2.4 on 2019-09-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_auto_20190723_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivopdf',
            old_name='agenda',
            new_name='paciente',
        ),
    ]
