# Generated by Django 2.2.4 on 2019-09-17 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_archivopdf_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='fecha_documento',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
