# Generated by Django 2.2.4 on 2019-09-24 06:27

from django.db import migrations, models
import paciente.models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_auto_20190917_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='archivo',
            field=models.FileField(blank=True, upload_to=paciente.models.Archivopdf._generar_ruta_archivo),
        ),
        migrations.AlterField(
            model_name='archivopdf',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
