# Generated by Django 2.2.4 on 2019-10-11 21:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_auto_20190924_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'NOTA'), (1, 'EXAMEN EXTERNO'), (2, 'CERTIFICADO MEDICO')], default=0)),
                ('fecha', models.DateField(auto_now=True)),
                ('fecha_documento', models.DateField(default=datetime.datetime.now)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
    ]
