# Generated by Django 2.2.4 on 2019-12-11 04:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopdf',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
