# Generated by Django 2.2.4 on 2019-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recdiagnostico_rechistoria_rectratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(default=0)),
                ('gestion', models.IntegerField(default=2007)),
                ('particular', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seguro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
