# Generated by Django 2.2.4 on 2019-08-07 22:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamento', '0001_initial'),
        ('servicio', '0001_initial'),
        ('seguro', '0001_initial'),
        ('paciente', '0009_auto_20190723_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2019, 8, 7, 18, 1, 6, 993571))),
                ('hora_fin', models.TimeField(blank=True, default=datetime.datetime(2019, 8, 7, 18, 1, 6, 993592))),
                ('estado', models.IntegerField(default=0)),
                ('prioridad', models.IntegerField(choices=[(0, 'LEVE'), (1, 'MODERADO'), (2, 'URGENTE')], default=0)),
                ('tipo', models.IntegerField(choices=[(0, 'PARTICULAR'), (1, 'SEGURO')], default=0)),
                ('procedencia', models.CharField(blank=True, max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=100)),
                ('tipo_beneficiario', models.CharField(choices=[('BENF', 'BENF'), ('ACT', 'ACT'), ('RENT', 'RENT')], default='BENF', max_length=10)),
                ('antocu', models.TextField(blank=True)),
                ('antsis', models.TextField(blank=True)),
                ('motivo', models.TextField(blank=True)),
                ('dsc', models.CharField(blank=True, max_length=50)),
                ('dcc', models.CharField(blank=True, max_length=50)),
                ('dre1', models.CharField(blank=True, max_length=50)),
                ('dre2', models.CharField(blank=True, max_length=50)),
                ('dre3', models.CharField(blank=True, max_length=50)),
                ('dau', models.CharField(blank=True, max_length=50)),
                ('ddc1', models.CharField(choices=[('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], default='J1', max_length=50)),
                ('ddc2', models.CharField(blank=True, max_length=50)),
                ('dph', models.CharField(blank=True, max_length=50)),
                ('dci', models.CharField(blank=True, max_length=50)),
                ('dcl', models.CharField(blank=True, max_length=50)),
                ('drc1', models.CharField(blank=True, max_length=50)),
                ('drc2', models.CharField(blank=True, max_length=50)),
                ('drc3', models.CharField(blank=True, max_length=50)),
                ('isc', models.CharField(blank=True, max_length=50)),
                ('icc', models.CharField(blank=True, max_length=50)),
                ('ire1', models.CharField(blank=True, max_length=50)),
                ('ire2', models.CharField(blank=True, max_length=50)),
                ('ire3', models.CharField(blank=True, max_length=50)),
                ('iau', models.CharField(blank=True, max_length=50)),
                ('idc1', models.CharField(choices=[('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], default='J1', max_length=50)),
                ('idc2', models.CharField(blank=True, max_length=50)),
                ('iph', models.CharField(blank=True, max_length=50)),
                ('ici', models.CharField(blank=True, max_length=50)),
                ('icl', models.CharField(blank=True, max_length=50)),
                ('irc1', models.CharField(blank=True, max_length=50)),
                ('irc2', models.CharField(blank=True, max_length=50)),
                ('irc3', models.CharField(blank=True, max_length=50)),
                ('adicion', models.CharField(blank=True, max_length=100)),
                ('dto', models.CharField(blank=True, max_length=50)),
                ('ito', models.CharField(blank=True, max_length=50)),
                ('dbio', models.TextField(blank=True)),
                ('ibio', models.TextField(blank=True)),
                ('dfdo', models.TextField(blank=True)),
                ('ifdo', models.TextField(blank=True)),
                ('otros', models.TextField(blank=True)),
                ('tipo_lente', models.TextField(blank=True)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('impav', models.BooleanField(default=False)),
                ('control', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.Seguro')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Reconsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('indicacion', models.TextField(blank=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Agendaserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=False)),
                ('descuento', models.BooleanField(default=False)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio')),
            ],
        ),
    ]
