# Generated by Django 2.1.4 on 2019-06-18 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('agenda', '0001_initial'), ('agenda', '0002_auto_20190128_1422'), ('agenda', '0003_auto_20190128_1425'), ('agenda', '0004_auto_20190128_1430'), ('agenda', '0005_auto_20190314_1503'), ('agenda', '0006_auto_20190326_2000'), ('agenda', '0007_auto_20190328_1457'), ('agenda', '0008_auto_20190408_1648'), ('agenda', '0009_auto_20190416_1625'), ('agenda', '0010_auto_20190422_1524'), ('agenda', '0011_auto_20190422_1617'), ('agenda', '0012_auto_20190422_1638'), ('agenda', '0013_auto_20190429_1606'), ('agenda', '0014_auto_20190429_1623'), ('agenda', '0015_auto_20190501_2055'), ('agenda', '0016_auto_20190503_2233'), ('agenda', '0017_auto_20190617_1641'), ('agenda', '0018_auto_20190617_1643'), ('agenda', '0019_auto_20190617_1645'), ('agenda', '0020_auto_20190617_1648'), ('agenda', '0021_auto_20190618_1101'), ('agenda', '0022_auto_20190618_1107'), ('agenda', '0023_auto_20190618_1108'), ('agenda', '0024_auto_20190618_1112'), ('agenda', '0025_auto_20190618_1113')]

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        ('seguro', '0001_initial'),
        ('paciente', '0003_auto_20190114_1959'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2019, 1, 28, 14, 21, 48, 161684))),
                ('hora_fin', models.TimeField(blank=True, default=datetime.datetime(2019, 1, 28, 14, 21, 48, 161708))),
                ('estado', models.IntegerField(default=0)),
                ('prioridad', models.IntegerField(choices=[(0, 'LEVE'), (1, 'MODERADO'), (2, 'URGENTE')], default=0)),
                ('tipo', models.IntegerField(choices=[(0, 'PARTICULAR'), (1, 'SEGURO')], default=0)),
                ('procedencia', models.CharField(blank=True, max_length=20)),
                ('antocu', models.TextField(blank=True)),
                ('antsis', models.TextField(blank=True)),
                ('motivo', models.TextField(blank=True)),
                ('dsc', models.CharField(blank=True, max_length=50)),
                ('dcc', models.CharField(blank=True, max_length=50)),
                ('dre1', models.CharField(blank=True, max_length=50)),
                ('dre2', models.CharField(blank=True, max_length=50)),
                ('dre3', models.CharField(blank=True, max_length=50)),
                ('dau', models.CharField(blank=True, max_length=50)),
                ('ddc1', models.CharField(blank=True, max_length=50)),
                ('ddc2', models.CharField(blank=True, max_length=50)),
                ('dph', models.CharField(blank=True, max_length=50)),
                ('dci', models.CharField(blank=True, max_length=50)),
                ('dcl', models.CharField(blank=True, max_length=50)),
                ('drc', models.CharField(blank=True, max_length=50)),
                ('isc', models.CharField(blank=True, max_length=50)),
                ('icc', models.CharField(blank=True, max_length=50)),
                ('ire1', models.CharField(blank=True, max_length=50)),
                ('ire2', models.CharField(blank=True, max_length=50)),
                ('ire3', models.CharField(blank=True, max_length=50)),
                ('iau', models.CharField(blank=True, max_length=50)),
                ('idc1', models.CharField(blank=True, max_length=50)),
                ('idc2', models.CharField(blank=True, max_length=50)),
                ('iph', models.CharField(blank=True, max_length=50)),
                ('ici', models.CharField(blank=True, max_length=50)),
                ('icl', models.CharField(blank=True, max_length=50)),
                ('irc', models.CharField(blank=True, max_length=50)),
                ('adicion', models.CharField(blank=True, max_length=100)),
                ('dto', models.CharField(blank=True, max_length=50)),
                ('ito', models.CharField(blank=True, max_length=50)),
                ('dbio', models.TextField(blank=True)),
                ('ibio', models.TextField(blank=True)),
                ('dfdo', models.TextField(blank=True)),
                ('ifdo', models.TextField(blank=True)),
                ('otros', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.Seguro')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 28, 14, 22, 28, 341170)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 1, 28, 14, 22, 28, 341146)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 28, 14, 25, 8, 466681)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 1, 28, 14, 25, 8, 466650)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 1, 28, 14, 30, 39, 556400)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 1, 28, 14, 30, 39, 556370)),
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo_lente',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 3, 14, 15, 3, 59, 155844)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 3, 14, 15, 3, 59, 155818)),
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='drc',
            new_name='drc1',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='irc',
            new_name='drc2',
        ),
        migrations.AddField(
            model_name='agenda',
            name='drc3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agenda',
            name='irc1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agenda',
            name='irc2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agenda',
            name='irc3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='ddc1',
            field=models.CharField(blank=True, choices=[('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 3, 26, 20, 0, 8, 339150)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 3, 26, 20, 0, 8, 339126)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='idc1',
            field=models.CharField(blank=True, choices=[('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 3, 28, 14, 57, 57, 887077)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 3, 28, 14, 57, 57, 887040)),
        ),
        migrations.AddField(
            model_name='agenda',
            name='matricula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo_beneficiario',
            field=models.CharField(choices=[('BENF', 'BENF'), ('ACT', 'ACT'), ('RENT', 'RENT')], default='BENF', max_length=10),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 8, 16, 48, 23, 460885)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 8, 16, 48, 23, 460862)),
        ),
        migrations.CreateModel(
            name='Agendaserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 16, 16, 25, 52, 989250)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 16, 16, 25, 52, 989224)),
        ),
        migrations.AddField(
            model_name='agendaserv',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
        ),
        migrations.AddField(
            model_name='agendaserv',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 22, 15, 24, 45, 341422)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 22, 15, 24, 45, 341397)),
        ),
        migrations.AddField(
            model_name='agendaserv',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agendaserv',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 22, 16, 17, 29, 815524)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 22, 16, 17, 29, 815502)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 22, 16, 38, 6, 453652)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 22, 16, 38, 6, 453619)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 29, 16, 6, 26, 70784)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 29, 16, 6, 26, 70762)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 29, 16, 23, 45, 629774)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 29, 16, 23, 45, 629754)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 5, 1, 20, 55, 19, 422207)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 5, 1, 20, 55, 19, 422185)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 5, 3, 22, 33, 1, 968028)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 5, 3, 22, 33, 1, 967999)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 17, 16, 41, 25, 126502)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 17, 16, 41, 25, 126479)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 17, 16, 43, 38, 918537)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 17, 16, 43, 38, 918514)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 17, 16, 45, 30, 346386)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 17, 16, 45, 30, 346364)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 17, 16, 48, 3, 874260)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 17, 16, 48, 3, 874237)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 18, 11, 1, 56, 652555)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 18, 11, 1, 56, 652513)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 18, 11, 7, 24, 507732)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 18, 11, 7, 24, 507710)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 18, 11, 8, 0, 71322)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 18, 11, 8, 0, 71300)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 18, 11, 12, 59, 381543)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 18, 11, 12, 59, 381522)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 6, 18, 11, 13, 57, 806234)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 6, 18, 11, 13, 57, 806208)),
        ),
    ]
