# Generated by Django 2.1.4 on 2019-01-28 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0003_auto_20190114_1959'),
        ('seguro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2019, 1, 28, 14, 21, 48, 161684))),
                ('hora_fin', models.TimeField(blank=True, default=datetime.datetime(2019, 1, 28, 14, 21, 48, 161708))),
                ('estado', models.IntegerField(default=0)),
                ('prioridad', models.IntegerField(choices=[(0, 'LEVE'), (1, 'MODERADO'), (2, 'URGENTE')], default=0)),
                ('tipo', models.IntegerField(choices=[(0, 'PARTICULAR'), (1, 'SEGURO')], default=0)),
                ('procedencia', models.CharField(blank=True, max_length=20)),
                ('antocu', models.TextField(blank=True)),
                ('antsis', models.TextField(blank=True)),
                ('motivo', models.TextField(blank=True)),
                ('dsc', models.CharField(blank=True, max_length=50)),
                ('dcc', models.CharField(blank=True, max_length=50)),
                ('dre1', models.CharField(blank=True, max_length=50)),
                ('dre2', models.CharField(blank=True, max_length=50)),
                ('dre3', models.CharField(blank=True, max_length=50)),
                ('dau', models.CharField(blank=True, max_length=50)),
                ('ddc1', models.CharField(blank=True, max_length=50)),
                ('ddc2', models.CharField(blank=True, max_length=50)),
                ('dph', models.CharField(blank=True, max_length=50)),
                ('dci', models.CharField(blank=True, max_length=50)),
                ('dcl', models.CharField(blank=True, max_length=50)),
                ('drc', models.CharField(blank=True, max_length=50)),
                ('isc', models.CharField(blank=True, max_length=50)),
                ('icc', models.CharField(blank=True, max_length=50)),
                ('ire1', models.CharField(blank=True, max_length=50)),
                ('ire2', models.CharField(blank=True, max_length=50)),
                ('ire3', models.CharField(blank=True, max_length=50)),
                ('iau', models.CharField(blank=True, max_length=50)),
                ('idc1', models.CharField(blank=True, max_length=50)),
                ('idc2', models.CharField(blank=True, max_length=50)),
                ('iph', models.CharField(blank=True, max_length=50)),
                ('ici', models.CharField(blank=True, max_length=50)),
                ('icl', models.CharField(blank=True, max_length=50)),
                ('irc', models.CharField(blank=True, max_length=50)),
                ('adicion', models.CharField(blank=True, max_length=100)),
                ('dto', models.CharField(blank=True, max_length=50)),
                ('ito', models.CharField(blank=True, max_length=50)),
                ('dbio', models.TextField(blank=True)),
                ('ibio', models.TextField(blank=True)),
                ('dfdo', models.TextField(blank=True)),
                ('ifdo', models.TextField(blank=True)),
                ('otros', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.Seguro')),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=200)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
    ]
