# Generated by Django 2.1.4 on 2019-07-05 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_squashed_0025_auto_20190618_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 7, 5, 14, 52, 23, 17215)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 7, 5, 14, 52, 23, 17192)),
        ),
    ]
