# Generated by Django 2.2.4 on 2019-08-07 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='fecha_consulta',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 7, 18, 22, 34, 568914)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 7, 18, 22, 34, 568890)),
        ),
    ]
