# Generated by Django 2.2.4 on 2019-08-08 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20190807_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 8, 17, 37, 52, 548128)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 8, 17, 37, 52, 548099)),
        ),
    ]
