# Generated by Django 2.2.4 on 2019-08-08 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190808_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 8, 17, 46, 47, 970429)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 8, 17, 46, 47, 970409)),
        ),
    ]
