# Generated by Django 2.1.4 on 2019-03-14 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190128_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='tipo_lente',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 3, 14, 15, 3, 59, 155844)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 3, 14, 15, 3, 59, 155818)),
        ),
    ]
