# Generated by Django 2.2.4 on 2019-08-08 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190808_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 8, 17, 53, 19, 327952)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 8, 17, 53, 19, 327931)),
        ),
    ]
