# Generated by Django 2.1.4 on 2019-03-27 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20190314_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='drc',
            new_name='drc1',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='irc',
            new_name='drc2',
        ),
        migrations.AddField(
            model_name='agenda',
            name='drc3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agenda',
            name='irc1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agenda',
            name='irc2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agenda',
            name='irc3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='ddc1',
            field=models.CharField(blank=True, choices=[('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 3, 26, 20, 0, 8, 339150)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 3, 26, 20, 0, 8, 339126)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='idc1',
            field=models.CharField(blank=True, choices=[('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], max_length=50),
        ),
    ]
