# Generated by Django 2.2.4 on 2019-08-14 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20190808_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 14, 17, 52, 3, 879071)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 14, 17, 52, 3, 879048)),
        ),
        migrations.AlterField(
            model_name='agendaserv',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
