# Generated by Django 2.2.4 on 2019-08-20 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20190814_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cobrar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 20, 19, 45, 34, 875106)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 20, 19, 45, 34, 875082)),
        ),
    ]
