# Generated by Django 2.1.4 on 2019-07-21 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20190719_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 7, 21, 17, 31, 16, 368972)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 7, 21, 17, 31, 16, 368949)),
        ),
        migrations.AddField(
            model_name='reconsulta',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
        ),
    ]
