# Generated by Django 2.1.4 on 2019-04-08 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20190328_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='matricula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo_beneficiario',
            field=models.IntegerField(choices=[(0, 'BENF'), (1, 'ACT'), (2, 'RENT')], default=0),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 8, 16, 48, 23, 460885)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 8, 16, 48, 23, 460862)),
        ),
    ]
