# Generated by Django 2.1.4 on 2019-04-16 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('agenda', '0008_auto_20190408_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendaserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 16, 16, 25, 52, 989250)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 16, 16, 25, 52, 989224)),
        ),
        migrations.AddField(
            model_name='agendaserv',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda'),
        ),
        migrations.AddField(
            model_name='agendaserv',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
    ]
