# Generated by Django 2.1.4 on 2019-07-21 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20190721_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='impav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 7, 21, 18, 52, 14, 543804)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 7, 21, 18, 52, 14, 543782)),
        ),
    ]
