# Generated by Django 2.2.4 on 2019-10-06 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20190924_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaserv',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='agenda',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 10, 6, 12, 37, 39, 393034)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 10, 6, 12, 37, 39, 393034)),
        ),
    ]
