# Generated by Django 2.1.4 on 2019-04-29 20:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20190422_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 29, 16, 6, 26, 70784)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 4, 29, 16, 6, 26, 70762)),
        ),
        migrations.AlterField(
            model_name='agendaserv',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendaserv',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
