# Generated by Django 2.2.4 on 2019-12-10 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_auto_20191011_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='ddc1',
            field=models.CharField(choices=[('', '--------'), ('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 12, 10, 17, 22, 20, 533915)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 12, 10, 17, 22, 20, 533915)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='idc1',
            field=models.CharField(choices=[('', '--------'), ('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], default='', max_length=50),
        ),
    ]
