# Generated by Django 2.2.1 on 2019-08-02 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_auto_20190723_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='ddc1',
            field=models.CharField(choices=[('J1', 'J1'), ('J2', 'J2'), ('J3', 'J3'), ('J4', 'J4'), ('J5', 'J5')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 2, 19, 1, 42, 410490)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 2, 19, 1, 42, 410456)),
        ),
        migrations.AlterField(
            model_name='reconsulta',
            name='detalle',
            field=models.TextField(),
        ),
    ]
