# Generated by Django 2.1.4 on 2019-05-04 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_auto_20190501_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 5, 3, 22, 33, 1, 968028)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 5, 3, 22, 33, 1, 967999)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo_beneficiario',
            field=models.CharField(choices=[('BENF', 'BENF'), ('ACT', 'ACT'), ('RENT', 'RENT')], default='BENF', max_length=10),
        ),
    ]
