# Generated by Django 2.2.1 on 2019-08-03 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_auto_20190803_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='control',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 8, 3, 1, 2, 25, 318827)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2019, 8, 3, 1, 2, 25, 318804)),
        ),
    ]
