# Generated by Django 2.1.4 on 2019-07-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('presentacion', models.IntegerField(choices=[(1, 'Solucion'), (2, 'Jarabe'), (3, 'Colirio'), (4, 'Locion'), (5, 'Linimento'), (6, 'Ovulo'), (7, 'Pomada'), (8, 'Crema'), (9, 'Capsula'), (10, 'Comprimido'), (11, 'Pildora'), (12, 'Gragea'), (13, 'Polvo'), (14, 'Supositorio')], default=1)),
                ('indicacion', models.TextField(blank=True)),
            ],
        ),
    ]
