# Generated by Django 2.2.4 on 2019-08-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
