# Generated by Django 2.2.8 on 2020-02-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguro', '0002_segurocosto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportegeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(default=0)),
                ('gestion', models.IntegerField(default=0)),
                ('particular', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seguro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporteseguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(default=0)),
                ('gestion', models.IntegerField(default=0)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.Seguro')),
            ],
        ),
    ]
