# Generated by Django 2.2.4 on 2019-08-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20190814_1752'),
        ('seguro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segurocosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguro.Seguro')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio')),
            ],
        ),
    ]
